### PR TITLE
check with new paradox

### PR DESCRIPTION
**Pull request by mb706**

### CODE REVIEW

**Comment by sebffischer** [comment]
Hey @pat-s, we are currently in the process of migrating to the new "S3 paradox". To release the new paradox on CRAN without breaking any reverse dependencies it would be great if you could merge this PR and make a new CRAN release! :)

**Comment by sebffischer** [comment]
The failing tests seem to be snapshot tests

**Comment by pat-s** [comment]
I have to make a new CRAN release in the next weeks anyhow as I got a mail from CRAN.

I wonder though why this change comes with a full CI suite change. If so, the other one would need to be removed. It looks like a central CI definition for the whole org, so it would likely be the best to adopt it.

The test failures also appear in `main`, so they are likely unrelated, yes.

**Comment by sebffischer** [comment]
Parts of the CI suite are intended to test with dev versions of paradox and bbotk to ensure that the old -> new paradox transition runs smoothly.

Regarding the org-wide CI definitions, they can be found here: https://github.com/mlr-org/actions

**Comment by pat-s** [comment]
@sebffischer Seems to work. Should this PR be included in the next release? I.e. is paradox waiting for all packages to be updated first?

**Comment by sebffischer** [comment]
@pat-s yes exactly, it would be great if you could include this in the next release!

**Comment by pat-s** [comment]
After the workflows were successfull, can I remove them again before merging? Or should I keep them around until paradox got updated?

**Comment by sebffischer** [comment]
Martin's idea is to have them in the main branch to ensure that any changes that are made to mlr3 packages before paradox is released are also tested against the new S3 paradox version. So ideally they should be kept there until paradox is released, but then they can be removed

**Pull request merged**
