### PR TITLE
chore: compatibility to mlr3 13.5

### PR DESCRIPTION
**Pull request by be-marc**

### CODE REVIEW

**Review by pat-s — COMMENTED** [review]
Thanks! Tests are still failing for the vignettes.

Can we integrate #209 in here?

**Comment by be-marc** [comment]
Don't you think that #209 is unnecessarily complicated? With a `rowwise_table`  you know directly what happens.

**Comment by pat-s** [comment]
> Don't you think that https://github.com/mlr-org/mlr3spatiotempcv/pull/209 is unnecessarily complicated? With a rowwise_table you know directly what happens.

I like it because it's dynamic and will prevent us from similar issues in the future. The other modifications down the line are written in a similar "append-like" fashion.

**Comment by be-marc** [comment]
What kind of similar problems do you mean?  `mlr_reflections` does not change daily and you don't have to react dynamically when it happens. I spend a few days fixing `mlr_reflections`. Just merge #207.

**Comment by pat-s** [comment]
It does not when it does, the package is not installable at all anymore (which is/was the case here). Manual action was required, otherwise the package failed during loading.

I don't see why we would not make it dynamic to avoid such issues in the future even if they are rare? #207 is not a blocker for #209 on the first look.

**Comment by be-marc** [comment]
> It does not when it does, the package is not installable at all anymore (which is/was the case here).

The package was not installable with mlr3 dev. There is no dependency on mlr3 dev in mlr3spatiotempcv. That was a mistake on yours. And when you merge this PR it works with mlr3 dev.

>  don't see why we would not make it dynamic to avoid such issues in the future even if they are rare?

You implemented `mlr_refelections$task_type` wrong ([L52-L54](https://github.com/mlr-org/mlr3spatiotempcv/blob/0ab1c36769ac30f07589cdf69f4b1fc58c6059af/R/zzz.R#L52-L54) and [L70-L71](https://github.com/mlr-org/mlr3spatiotempcv/blob/0ab1c36769ac30f07589cdf69f4b1fc58c6059af/R/zzz.R#L70-L71)) and now you want to add a function that makes it even more complicated to spot such bugs. Maybe try to understand https://github.com/mlr-org/mlr3/pull/842 and you get why #209 is a bad idea.

**Pull request merged**
