### PR TITLE
- Add `as_task_*` S3 generics

### PR DESCRIPTION
**Pull request by mllg**
Missing:

* method `as_task_classif.TaskClassifST()`
* method `as_task_classif_st.TaskClassif()`
* `as_task_regr_st()` generic + methods

### CODE REVIEW

**Comment by pat-s** [comment]
Thanks.

I am planning a CRAN release in the next 7 days due to CRAN errors on Solaris.

Do you want to have that included by then?

**Comment by mllg** [comment]
It does not break stuff on my side, so no hurry. Would just be good to have in the long run so that the documentation is consistent.

**Comment by pat-s** [comment]
@mllg Added all methods, please have a look.

**Comment by mllg** [comment]
LGTM.

**Pull request merged**
